theme = "space-villain"
icons = "awesome"

[[block]]
block = "music"
buttons = ["prev", "play", "next"]

[[block]]
block = "maildir"
interval = 60
inboxes = ["~/.mail"]
threshold_warning = 1
threshold_critical = 10
display_type = "new"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

# [[block]]
# block = "memory"
# display_type = "memory"
# format_mem = "{mem_total_used_percents}"
# format_swap = "{swap_used_percents}"

# [[block]]
# block = "cpu"
# interval = 5

# [[block]]
# block = "load"
# interval = 5
# format = "{1m}"

# [[block]]
# block = "net"
# interval = 5

# [[block]]
# block = "networkmanager"
# primary_only = true
# on_click = "x-terminal-emulator -e nmtui"
# ap_format = "{ssid^10}"
# device_format = "{icon}"

[[block]]
block = "sound"
format = "{output_description^5} {volume}"
on_click = "pavucontrol"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
