# theme = "space-villain"
# icons = "awesome"

[[block]]
block = "maildir"
interval = 60
inboxes = ["/home/matthew/.mail/spectrust/Inbox"]
threshold_warning = 1
threshold_critical = 10
display_type = "new"
on_click = "emacsclient --create-frame --eval '(mu4e)'"

[[block]]
block = "music"
buttons = ["prev", "play", "next"]

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

# [[block]]
# block = "memory"
# display_type = "memory"
# format_mem = "{mem_total_used_percents}"
# format_swap = "{swap_used_percents}"

# [[block]]
# block = "cpu"
# interval = 5

# [[block]]
# block = "load"
# interval = 5
# format = "{1m}"

# [[block]]
# block = "net"
# interval = 5

# [[block]]
# block = "networkmanager"
# primary_only = true
# # on_click = "x-terminal-emulator -e nmtui"
# on_click = "emacsclient --create-frame --eval '(my/run-in-vterm \"nmtui\")'"
# ap_format = "{ssid^5}"
# device_format = "{icon}"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|Wired connection} via $device "

[[block]]
block = "sound"
format = "{output_description^3} {volume}"
on_click = "pavucontrol"

[[block]]
block = "battery"
interval = 60
format = "{percentage} {time}"

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %R"
on_click = "emacsclient --eval '(calendar)'"
